sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Alchohol' AND Product = 'beer' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Alchohol' AND Product = 'Vodka' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Alchohol' AND Product = 'whiskey' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Alchohol' AND Product = 'Rum' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Alchohol' AND Product = 'Tequila' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Footwear' AND Product = 'sneakers' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Footwear' AND Product = 'sports shoes' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Footwear' AND Product = 'sandals' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Footwear' AND Product = 'heels' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Footwear' AND Product = 'boots' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Footwear' AND Product = 'spike shoes' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Accessories' AND Product = 'aviator' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Accessories' AND Product = 'wayfarer' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Accessories' AND Product = 'digital watch' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Accessories' AND Product = 'skeleton watch' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Accessories' AND Product = 'analog watch' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Accessories' AND Product = 'leather wallet' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Electronics' AND Product = 'dslr' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Electronics' AND Product = 'tablet PC' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Electronics' AND Product = 'playstation' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Bags' AND Product = 'laptop bag' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Bags' AND Product = 'RuckSack' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Bags' AND Product = 'travel bag' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Bags' AND Product = 'duffle bag' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Bags' AND Product = 'sling bag' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Female Bags' AND Product = 'bucket bag' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Female Bags' AND Product = 'clutch bag' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Female Bags' AND Product = 'hobo bag' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Female Bags' AND Product = 'fold over clutch' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Female Bags' AND Product = 'messenger bag' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Female Bags' AND Product = 'Minaudiere' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Female Bags' AND Product = 'Satchel' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Female Bags' AND Product = 'Wristlet' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Skating and Skiing' AND Product = 'SkateBoard' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Skating and Skiing' AND Product = 'roller skates' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Skating and Skiing' AND Product = 'hover board' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Skating and Skiing' AND Product = 'electric Scooter' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Skating and Skiing' AND Product = 'Surfing Board' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Cosmetics' AND Product = 'Hairgel' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Cosmetics' AND Product = 'hairspray' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Cosmetics' AND Product = 'hairoil' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Cosmetics' AND Product = 'sunscreen' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Cosmetics' AND Product = 'bodyspray' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Cosmetics' AND Product = 'showergel' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Cosmetics' AND Product = 'shampoo' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Cosmetics' AND Product = 'moisturizer' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Cosmetics' AND Product = 'lipstick' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Cosmetics' AND Product = 'eyeliner' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Cosmetics' AND Product = 'lipgloss' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Drinks' AND Product = 'Juice' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Drinks' AND Product = 'Tea' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Drinks' AND Product = 'Coffee' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Milk' AND Product = 'Whole milk' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Milk' AND Product = 'flavored milk' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Milk' AND Product = 'lactose free milk' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Milk' AND Product = 'buttermilk' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Chocs' AND Product = 'Cookie' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Chocs' AND Product = 'Donut' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Chocs' AND Product = 'pastry' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Chocs' AND Product = 'cheesecake' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Chocs' AND Product = 'pancake' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Chocs' AND Product = 'icecream' ").collect().foreach(println);
sqlContext.sql("SELECT SUM(Review) FROM product_dynamic_partition WHERE Category = 'Chocs' AND Product = 'chocolate' ").collect().foreach(println);